class ArabicNumberModel {
  final String number;
  final String word;

  const ArabicNumberModel({required this.number, required this.word});

  static List<ArabicNumberModel> numbers = [
    const ArabicNumberModel(number: '٠', word: 'صفر'),
    const ArabicNumberModel(number: '١', word: 'واحد'),
    const ArabicNumberModel(number: '٢', word: 'اثنان'),
    const ArabicNumberModel(number: '٣', word: 'ثلاثة'),
    const ArabicNumberModel(number: '٤', word: 'أربعة'),
    const ArabicNumberModel(number: '٥', word: 'خمسة'),
    const ArabicNumberModel(number: '٦', word: 'ستة'),
    const ArabicNumberModel(number: '٧', word: 'سبعة'),
    const ArabicNumberModel(number: '٨', word: 'ثمانية'),
    const ArabicNumberModel(number: '٩', word: 'تسعة'),
    const ArabicNumberModel(number: '١٠', word: 'عشرة'),
    const ArabicNumberModel(number: '١١', word: 'أحد عشر'),
    const ArabicNumberModel(number: '١٢', word: 'اثنا عشر'),
    const ArabicNumberModel(number: '١٣', word: 'ثلاثة عشر'),
    const ArabicNumberModel(number: '١٤', word: 'أربعة عشر'),
    const ArabicNumberModel(number: '١٥', word: 'خمسة عشر'),
    const ArabicNumberModel(number: '١٦', word: 'ستة عشر'),
    const ArabicNumberModel(number: '١٧', word: 'سبعة عشر'),
    const ArabicNumberModel(number: '١٨', word: 'ثمانية عشر'),
    const ArabicNumberModel(number: '١٩', word: 'تسعة عشر'),
    const ArabicNumberModel(number: '٢٠', word: 'عشرون'),
    const ArabicNumberModel(number: '٢١', word: 'واحد وعشرون'),
    const ArabicNumberModel(number: '٢٢', word: 'اثنان وعشرون'),
    const ArabicNumberModel(number: '٢٣', word: 'ثلاثة وعشرون'),
    const ArabicNumberModel(number: '٢٤', word: 'أربعة وعشرون'),
    const ArabicNumberModel(number: '٢٥', word: 'خمسة وعشرون'),
    const ArabicNumberModel(number: '٢٦', word: 'ستة وعشرون'),
    const ArabicNumberModel(number: '٢٧', word: 'سبعة وعشرون'),
    const ArabicNumberModel(number: '٢٨', word: 'ثمانية وعشرون'),
    const ArabicNumberModel(number: '٢٩', word: 'تسعة وعشرون'),
    const ArabicNumberModel(number: '٣٠', word: 'ثلاثون'),
    const ArabicNumberModel(number: '٣١', word: 'واحد وثلاثون'),
    const ArabicNumberModel(number: '٣٢', word: 'اثنان وثلاثون'),
    const ArabicNumberModel(number: '٣٣', word: 'ثلاثة وثلاثون'),
    const ArabicNumberModel(number: '٣٤', word: 'أربعة وثلاثون'),
    const ArabicNumberModel(number: '٣٥', word: 'خمسة وثلاثون'),
    const ArabicNumberModel(number: '٣٦', word: 'ستة وثلاثون'),
    const ArabicNumberModel(number: '٣٧', word: 'سبعة وثلاثون'),
    const ArabicNumberModel(number: '٣٨', word: 'ثمانية وثلاثون'),
    const ArabicNumberModel(number: '٣٩', word: 'تسعة وثلاثون'),
    const ArabicNumberModel(number: '٤٠', word: 'أربعون'),
    const ArabicNumberModel(number: '٤١', word: 'واحد وأربعون'),
    const ArabicNumberModel(number: '٤٢', word: 'اثنان وأربعون'),
    const ArabicNumberModel(number: '٤٣', word: 'ثلاثة وأربعون'),
    const ArabicNumberModel(number: '٤٤', word: 'أربعة وأربعون'),
    const ArabicNumberModel(number: '٤٥', word: 'خمسة وأربعون'),
    const ArabicNumberModel(number: '٤٦', word: 'ستة وأربعون'),
    const ArabicNumberModel(number: '٤٧', word: 'سبعة وأربعون'),
    const ArabicNumberModel(number: '٤٨', word: 'ثمانية وأربعون'),
    const ArabicNumberModel(number: '٤٩', word: 'تسعة وأربعون'),
    const ArabicNumberModel(number: '٥٠', word: 'خمسون'),
    const ArabicNumberModel(number: '٥١', word: 'واحد وخمسون'),
    const ArabicNumberModel(number: '٥٢', word: 'اثنان وخمسون'),
    const ArabicNumberModel(number: '٥٣', word: 'ثلاثة وخمسون'),
    const ArabicNumberModel(number: '٥٤', word: 'أربعة وخمسون'),
    const ArabicNumberModel(number: '٥٥', word: 'خمسة وخمسون'),
    const ArabicNumberModel(number: '٥٦', word: 'ستة وخمسون'),
    const ArabicNumberModel(number: '٥٧', word: 'سبعة وخمسون'),
    const ArabicNumberModel(number: '٥٨', word: 'ثمانية وخمسون'),
    const ArabicNumberModel(number: '٥٩', word: 'تسعة وخمسون'),
    const ArabicNumberModel(number: '٦٠', word: 'ستون'),
    const ArabicNumberModel(number: '٦١', word: 'واحد وستون'),
    const ArabicNumberModel(number: '٦٢', word: 'اثنان وستون'),
    const ArabicNumberModel(number: '٦٣', word: 'ثلاثة وستون'),
    const ArabicNumberModel(number: '٦٤', word: 'أربعة وستون'),
    const ArabicNumberModel(number: '٦٥', word: 'خمسة وستون'),
    const ArabicNumberModel(number: '٦٦', word: 'ستة وستون'),
    const ArabicNumberModel(number: '٦٧', word: 'سبعة وستون'),
    const ArabicNumberModel(number: '٦٨', word: 'ثمانية وستون'),
    const ArabicNumberModel(number: '٦٩', word: 'تسعة وستون'),
    const ArabicNumberModel(number: '٧٠', word: 'سبعون'),
    const ArabicNumberModel(number: '٧١', word: 'واحد وسبعون'),
    const ArabicNumberModel(number: '٧٢', word: 'اثنان وسبعون'),
    const ArabicNumberModel(number: '٧٣', word: 'ثلاثة وسبعون'),
    const ArabicNumberModel(number: '٧٤', word: 'أربعة وسبعون'),
    const ArabicNumberModel(number: '٧٥', word: 'خمسة وسبعون'),
    const ArabicNumberModel(number: '٧٦', word: 'ستة وسبعون'),
    const ArabicNumberModel(number: '٧٧', word: 'سبعة وسبعون'),
    const ArabicNumberModel(number: '٧٨', word: 'ثمانية وسبعون'),
    const ArabicNumberModel(number: '٧٩', word: 'تسعة وسبعون'),
    const ArabicNumberModel(number: '٨٠', word: 'ثمانون'),
    const ArabicNumberModel(number: '٨١', word: 'واحد وثمانون'),
    const ArabicNumberModel(number: '٨٢', word: 'اثنان وثمانون'),
    const ArabicNumberModel(number: '٨٣', word: 'ثلاثة وثمانون'),
    const ArabicNumberModel(number: '٨٤', word: 'أربعة وثمانون'),
    const ArabicNumberModel(number: '٨٥', word: 'خمسة وثمانون'),
    const ArabicNumberModel(number: '٨٦', word: 'ستة وثمانون'),
    const ArabicNumberModel(number: '٨٧', word: 'سبعة وثمانون'),
    const ArabicNumberModel(number: '٨٨', word: 'ثمانية وثمانون'),
    const ArabicNumberModel(number: '٨٩', word: 'تسعة وثمانون'),
    const ArabicNumberModel(number: '٩٠', word: 'تسعون'),
    const ArabicNumberModel(number: '٩١', word: 'واحد وتسعون'),
    const ArabicNumberModel(number: '٩٢', word: 'اثنان وتسعون'),
    const ArabicNumberModel(number: '٩٣', word: 'ثلاثة وتسعون'),
    const ArabicNumberModel(number: '٩٤', word: 'أربعة وتسعون'),
    const ArabicNumberModel(number: '٩٥', word: 'خمسة وتسعون'),
    const ArabicNumberModel(number: '٩٦', word: 'ستة وتسعون'),
    const ArabicNumberModel(number: '٩٧', word: 'سبعة وتسعون'),
    const ArabicNumberModel(number: '٩٨', word: 'ثمانية وتسعون'),
    const ArabicNumberModel(number: '٩٩', word: 'تسعة وتسعون'),
    const ArabicNumberModel(number: '١٠٠', word: 'مائة'),
  ];
}
